// Soal simulasi ASAT PKN Kelas 2 SD
// Disusun sesuai kisi-kisi (20 indikator) di README.md
// Bahasa dibuat sederhana & ramah untuk anak kelas 2.
// answer = index jawaban benar (0-3). emoji = maskot pendamping soal.

export const QUESTIONS = [
  {
    tag: "Musyawarah",
    emoji: "💜",
    text: "Keluarga ingin memilih tempat liburan. Cara terbaik memutuskannya adalah…",
    options: ["Bertengkar", "Musyawarah bersama", "Ikut mau Ayah saja", "Diundi diam-diam"],
    answer: 1,
    why: "Hebat! Musyawarah artinya berunding bersama supaya semua senang. 💜",
  },
  {
    tag: "Lambang Pancasila",
    emoji: "🦅",
    text: "Semboyan yang tertulis pada pita burung Garuda adalah…",
    options: ["Bhinneka Tunggal Ika", "Maju Terus", "Rajin Pangkal Pandai", "Hemat Pangkal Kaya"],
    answer: 0,
    why: "Betul! 'Bhinneka Tunggal Ika' artinya berbeda-beda tetapi tetap satu. 🦅",
  },
  {
    tag: "Nilai Pancasila",
    emoji: "🙏",
    text: "Berdoa sebelum belajar adalah pengamalan Pancasila sila ke…",
    options: ["Pertama", "Kedua", "Ketiga", "Kelima"],
    answer: 0,
    why: "Yes! Beribadah dan berdoa adalah sila pertama. ⭐",
  },
  {
    tag: "Manfaat Pancasila",
    emoji: "🕊️",
    text: "Jika semua orang mengamalkan Pancasila, kehidupan menjadi…",
    options: ["Ramai bertengkar", "Rukun dan damai", "Sepi sekali", "Banyak musuh"],
    answer: 1,
    why: "Benar! Pancasila membuat hidup rukun dan damai. 🕊️",
  },
  {
    tag: "Kewajiban di Rumah",
    emoji: "🏠",
    text: "Salah satu kewajiban anak di rumah adalah…",
    options: ["Main terus", "Merapikan tempat tidur sendiri", "Menyuruh adik kerja", "Tidur seharian"],
    answer: 1,
    why: "Pintar! Merapikan tempat tidur itu tugas yang baik. 🛏️",
  },
  {
    tag: "Peran Ayah",
    emoji: "👨",
    text: "Tugas utama seorang ayah dalam keluarga biasanya…",
    options: ["Mencari nafkah", "Bermain game", "Tidur saja", "Jalan-jalan terus"],
    answer: 0,
    why: "Tepat! Ayah bekerja mencari nafkah untuk keluarga. 👨‍👧",
  },
  {
    tag: "Hak & Kewajiban",
    emoji: "⚖️",
    text: "Jika hak dan kewajiban dilakukan seimbang, hidup menjadi…",
    options: ["Tertib dan bahagia", "Berantakan", "Sedih", "Sendirian"],
    answer: 0,
    why: "Betul! Seimbang itu membuat hidup tertib dan bahagia. ⚖️",
  },
  {
    tag: "Kewajiban di Sekolah",
    emoji: "🏫",
    text: "Menjaga kebersihan sekolah dilakukan dengan…",
    options: ["Membuang sampah sembarangan", "Mencoret tembok", "Membuang sampah di tempatnya", "Membiarkan kotor"],
    answer: 2,
    why: "Hore! Buang sampah pada tempatnya membuat sekolah bersih. 🧹",
  },
  {
    tag: "Hidup Harmonis",
    emoji: "🤝",
    text: "Kalau semua mematuhi hak dan kewajiban, suasana menjadi…",
    options: ["Harmonis dan rukun", "Penuh marah", "Berisik", "Menakutkan"],
    answer: 0,
    why: "Yes! Mematuhi aturan membuat hidup harmonis. 🤝",
  },
  {
    tag: "Keberagaman",
    emoji: "🌈",
    text: "Saat punya teman yang berbeda-beda, sebaiknya kita…",
    options: ["Mengejek", "Saling menghargai", "Menjauhi", "Memilih-milih teman"],
    answer: 1,
    why: "Benar! Menghargai keberagaman membuat kita rukun. 🌈",
  },
  {
    tag: "Persatuan",
    emoji: "🧩",
    text: "Persatuan artinya…",
    options: ["Bercerai-berai", "Bersatu menjadi satu", "Saling menjauh", "Sendiri-sendiri"],
    answer: 1,
    why: "Tepat! Persatuan berarti bersatu menjadi satu. 🧩",
  },
  {
    tag: "Peran Sekolah",
    emoji: "📚",
    text: "Di sekolah kita diajarkan untuk…",
    options: ["Bertengkar", "Hidup bersatu dan saling menghormati", "Menang sendiri", "Pelit berbagi"],
    answer: 1,
    why: "Hebat! Sekolah mengajarkan hidup bersatu. 📚",
  },
  {
    tag: "Toleransi",
    emoji: "💞",
    text: "Saat teman beribadah dengan cara berbeda, sikap kita…",
    options: ["Mengganggu", "Menghormati", "Menertawakan", "Memaksa ikut kita"],
    answer: 1,
    why: "Betul! Menghormati teman = toleransi yang baik. 💞",
  },
  {
    tag: "Menjaga Lingkungan Sekolah",
    emoji: "🌱",
    text: "Cara menjaga lingkungan sekolah misalnya…",
    options: ["Menginjak tanaman", "Piket dan menyiram tanaman", "Membuang sampah di laci", "Mencoret meja"],
    answer: 1,
    why: "Pintar! Piket dan merawat tanaman menjaga sekolah. 🌱",
  },
  {
    tag: "Gotong Royong",
    emoji: "🧹",
    text: "Manfaat gotong royong adalah pekerjaan menjadi…",
    options: ["Lebih cepat selesai", "Makin berat", "Tidak selesai", "Membosankan"],
    answer: 0,
    why: "Yes! Gotong royong membuat pekerjaan cepat selesai. 🧹",
  },
  {
    tag: "Lambang Persatuan",
    emoji: "🌳",
    text: "Lambang sila ketiga (Persatuan Indonesia) adalah pohon…",
    options: ["Beringin", "Kelapa", "Mangga", "Pisang"],
    answer: 0,
    why: "Betul! Pohon beringin melambangkan persatuan. 🌳",
  },
  {
    tag: "Kerja Kelompok",
    emoji: "👫",
    text: "Saat mengerjakan tugas kelompok kita harus…",
    options: ["Bekerja sama", "Diam saja", "Main sendiri", "Menyontek teman"],
    answer: 0,
    why: "Hore! Kerja kelompok harus bekerja sama. 👫",
  },
  {
    tag: "Manfaat Persatuan",
    emoji: "💪",
    text: "Manfaat menjaga persatuan adalah negara menjadi…",
    options: ["Lemah", "Kuat dan aman", "Mudah pecah", "Sepi"],
    answer: 1,
    why: "Tepat! Bersatu membuat negara kuat dan aman. 💪",
  },
  {
    tag: "Merawat Lingkungan",
    emoji: "✏️",
    text: "Sikap yang benar terhadap dinding sekolah adalah…",
    options: ["Mencoret-coret", "Tidak mencoret dan menjaganya", "Menempel permen karet", "Memukulnya"],
    answer: 1,
    why: "Benar! Dinding sekolah harus dijaga bersih. ✨",
  },
  {
    tag: "Tujuan Persatuan",
    emoji: "🇮🇩",
    text: "Tujuan persatuan adalah supaya kita…",
    options: ["Mudah dipecah belah", "Hidup rukun dan tidak mudah dipecah", "Saling bermusuhan", "Berpisah"],
    answer: 1,
    why: "Hebat sekali! Persatuan membuat kita rukun dan kuat. 🇮🇩",
  },
];
